/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_ANDROID_PROTOLOG_PZC_H_
#define INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_ANDROID_PROTOLOG_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "../../common/protolog_common.pzc.h"
#include "perfetto/public/pb_macros.h"

PERFETTO_PB_MSG_DECL(perfetto_protos_ProtoLogViewerConfig_Group);
PERFETTO_PB_MSG_DECL(perfetto_protos_ProtoLogViewerConfig_MessageData);

PERFETTO_PB_MSG(perfetto_protos_ProtoLogViewerConfig);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogViewerConfig,
                  MSG,
                  perfetto_protos_ProtoLogViewerConfig_MessageData,
                  messages,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogViewerConfig,
                  MSG,
                  perfetto_protos_ProtoLogViewerConfig_Group,
                  groups,
                  2);

PERFETTO_PB_MSG(perfetto_protos_ProtoLogViewerConfig_Group);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogViewerConfig_Group,
                  VARINT,
                  uint32_t,
                  id,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogViewerConfig_Group,
                  STRING,
                  const char*,
                  name,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogViewerConfig_Group,
                  STRING,
                  const char*,
                  tag,
                  3);

PERFETTO_PB_MSG(perfetto_protos_ProtoLogViewerConfig_MessageData);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogViewerConfig_MessageData,
                  FIXED64,
                  uint64_t,
                  message_id,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogViewerConfig_MessageData,
                  STRING,
                  const char*,
                  message,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogViewerConfig_MessageData,
                  VARINT,
                  enum perfetto_protos_ProtoLogLevel,
                  level,
                  3);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogViewerConfig_MessageData,
                  VARINT,
                  uint32_t,
                  group_id,
                  4);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogViewerConfig_MessageData,
                  STRING,
                  const char*,
                  location,
                  5);

PERFETTO_PB_MSG(perfetto_protos_ProtoLogMessage);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogMessage,
                  FIXED64,
                  uint64_t,
                  message_id,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogMessage,
                  VARINT,
                  uint32_t,
                  str_param_iids,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogMessage,
                  ZIGZAG,
                  int64_t,
                  sint64_params,
                  3);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogMessage,
                  FIXED64,
                  double,
                  double_params,
                  4);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogMessage,
                  VARINT,
                  int32_t,
                  boolean_params,
                  5);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogMessage,
                  VARINT,
                  uint32_t,
                  stacktrace_iid,
                  6);

#endif  // INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_ANDROID_PROTOLOG_PZC_H_
