# HUB devices are always allowed, in any system state.
# Per https://www.usb.org/defined-class-codes, HUBs are 09h class, 00h sub-class
#
# Composite HUB devices will need to be authorized before they can be used.
allow with-interface equals { 09:00:* }

# Internal devices are also always allowed and must be properly labelled by vendors.
# This will be enforced via GTS testing.
allow internal-device

# All USB devices are allowed when the Set-up wizard is active.
# This should only be running before the first user is configured. For compatibility and
# making sure accessibility devices correctly set up, this seems reasonable.
allow when Setup

# Use vendor allowlist in debuggable images for more stable ADB connections.
import-allowlist vendor when debuggable

# When in login screen (before first sign-in/unlock), we allow adding new HID devices
# by Asking.
ask with-interface one-of {03:*:*} when Booted

# All other devices can only connect during Booted or ScreenLocked if they have
# previously been trusted.
allow-persisted when one-of {Booted, ScreenLocked}

# All other devices must ASK when logged in. Persisted devices will allow without showing
# any UI dialog.
ask when LoggedIn

# Everything else gets deferred. This is the default rule.
# Defer means to take no action on authorization and re-evaluate on state change.
#
# If the device is newly connected, the "default authorization" would leave this device
# in a denied state.
# If the device was previously connected and authorized, it will remain authorized.
defer

