# USB Auth Policy for desktop devices.

# HUB and HID devices are always allowed, in any system state.
allow with-interface any-of { 03:*:*, 09:*:* }

# Internal devices are also always allowed
allow internal-device

# We should also allow ethernet devices during setup and login screen
# CDC-NCM (02:0D:*), RNDIS all protocols (EF:04:*)
allow with-interface any-of { 02:0D:*, EF:04:* } when any-of { Setup, Booted }

# Allow Realtek USB ethernet adapter
allow with-id 0bda:8153 when any-of { Setup, Booted }

# Allow Servo
allow with-id 04b4:6502 when any-of { Setup, Booted }
# Virtual keyboard
allow with-id 03eb:2042 when any-of { Setup, Booted }

# Allow Fibocom FM101 modem
allow with-id 2cb7:01a2 when any-of { Setup, Booted }

# Allow USB TO USB ADB Cable
allow with-id 18d1:27a7 when any-of { Setup, Booted }

# All other devices are allowed when logged in
allow when LoggedIn

# Defer decisions when screen is locked
defer when ScreenLocked

# Everything else gets deferred. This is the default rule.
# TODO (b/477348210): Temporarily set to Allow by default to support staging flags.
# We will revert to defer once build flags are decoupled from runtime auth.
allow
