/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_PROFILING_PROFILE_COMMON_PZC_H_
#define INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_PROFILING_PROFILE_COMMON_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "perfetto/public/pb_macros.h"

PERFETTO_PB_MSG_DECL(perfetto_protos_AddressSymbols);
PERFETTO_PB_MSG_DECL(perfetto_protos_Line);

PERFETTO_PB_MSG(perfetto_protos_Callstack);
PERFETTO_PB_FIELD(perfetto_protos_Callstack, VARINT, uint64_t, iid, 1);
PERFETTO_PB_FIELD(perfetto_protos_Callstack, VARINT, uint64_t, frame_ids, 2);

PERFETTO_PB_MSG(perfetto_protos_Frame);
PERFETTO_PB_FIELD(perfetto_protos_Frame, VARINT, uint64_t, iid, 1);
PERFETTO_PB_FIELD(perfetto_protos_Frame, VARINT, uint64_t, function_name_id, 2);
PERFETTO_PB_FIELD(perfetto_protos_Frame, VARINT, uint64_t, mapping_id, 3);
PERFETTO_PB_FIELD(perfetto_protos_Frame, VARINT, uint64_t, rel_pc, 4);
PERFETTO_PB_FIELD(perfetto_protos_Frame, VARINT, uint64_t, source_path_iid, 5);
PERFETTO_PB_FIELD(perfetto_protos_Frame, VARINT, uint32_t, line_number, 6);

PERFETTO_PB_MSG(perfetto_protos_Mapping);
PERFETTO_PB_FIELD(perfetto_protos_Mapping, VARINT, uint64_t, iid, 1);
PERFETTO_PB_FIELD(perfetto_protos_Mapping, VARINT, uint64_t, build_id, 2);
PERFETTO_PB_FIELD(perfetto_protos_Mapping, VARINT, uint64_t, exact_offset, 8);
PERFETTO_PB_FIELD(perfetto_protos_Mapping, VARINT, uint64_t, start_offset, 3);
PERFETTO_PB_FIELD(perfetto_protos_Mapping, VARINT, uint64_t, start, 4);
PERFETTO_PB_FIELD(perfetto_protos_Mapping, VARINT, uint64_t, end, 5);
PERFETTO_PB_FIELD(perfetto_protos_Mapping, VARINT, uint64_t, load_bias, 6);
PERFETTO_PB_FIELD(perfetto_protos_Mapping,
                  VARINT,
                  uint64_t,
                  path_string_ids,
                  7);

PERFETTO_PB_MSG(perfetto_protos_ModuleSymbols);
PERFETTO_PB_FIELD(perfetto_protos_ModuleSymbols, STRING, const char*, path, 1);
PERFETTO_PB_FIELD(perfetto_protos_ModuleSymbols,
                  STRING,
                  const char*,
                  build_id,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_ModuleSymbols,
                  MSG,
                  perfetto_protos_AddressSymbols,
                  address_symbols,
                  3);

PERFETTO_PB_MSG(perfetto_protos_AddressSymbols);
PERFETTO_PB_FIELD(perfetto_protos_AddressSymbols, VARINT, uint64_t, address, 1);
PERFETTO_PB_FIELD(perfetto_protos_AddressSymbols,
                  MSG,
                  perfetto_protos_Line,
                  lines,
                  2);

PERFETTO_PB_MSG(perfetto_protos_Line);
PERFETTO_PB_FIELD(perfetto_protos_Line, STRING, const char*, function_name, 1);
PERFETTO_PB_FIELD(perfetto_protos_Line,
                  STRING,
                  const char*,
                  source_file_name,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_Line, VARINT, uint32_t, line_number, 3);

PERFETTO_PB_MSG(perfetto_protos_InternedString);
PERFETTO_PB_FIELD(perfetto_protos_InternedString, VARINT, uint64_t, iid, 1);
PERFETTO_PB_FIELD(perfetto_protos_InternedString, STRING, const char*, str, 2);

#endif  // INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_PROFILING_PROFILE_COMMON_PZC_H_
