/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_PERFETTO_PUBLIC_PROTOS_CONFIG_ANDROID_PROTOLOG_CONFIG_PZC_H_
#define INCLUDE_PERFETTO_PUBLIC_PROTOS_CONFIG_ANDROID_PROTOLOG_CONFIG_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "../../common/protolog_common.pzc.h"
#include "perfetto/public/pb_macros.h"

PERFETTO_PB_MSG_DECL(perfetto_protos_ProtoLogGroup);

PERFETTO_PB_ENUM_IN_MSG(perfetto_protos_ProtoLogConfig, TracingMode){
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_ProtoLogConfig, DEFAULT) = 0,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_ProtoLogConfig,
                                  ENABLE_ALL) = 1,
};

PERFETTO_PB_MSG(perfetto_protos_ProtoLogGroup);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogGroup,
                  STRING,
                  const char*,
                  group_name,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogGroup,
                  VARINT,
                  enum perfetto_protos_ProtoLogLevel,
                  log_from,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogGroup,
                  VARINT,
                  bool,
                  collect_stacktrace,
                  3);

PERFETTO_PB_MSG(perfetto_protos_ProtoLogConfig);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogConfig,
                  MSG,
                  perfetto_protos_ProtoLogGroup,
                  group_overrides,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogConfig,
                  VARINT,
                  enum perfetto_protos_ProtoLogConfig_TracingMode,
                  tracing_mode,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_ProtoLogConfig,
                  VARINT,
                  enum perfetto_protos_ProtoLogLevel,
                  default_log_from_level,
                  3);

#endif  // INCLUDE_PERFETTO_PUBLIC_PROTOS_CONFIG_ANDROID_PROTOLOG_CONFIG_PZC_H_
